### ISSUE TITLE
Version 20.08 does not expose /app/tools/podman

### ISSUE THREAD

**Issue by peacememories** [flathub/com.visualstudio.code.tool.podman#13]
I've been playing around with this package for a bit, and what I've found is: When I try to install it, flatpak asks me whether I want to use brnach `20.08` or `21.08`. If I choose `20.08`, I do not get the `podman-remote` binary exposed in vscode. When I choose `21.08` I do get the binary, and it seems to be able to connect to my podman socket, but it then tells me that my podman server is too old.
I'm currently running Fedora Silverblue 35, which comes with podman 3.4.4, while the podman tool expects 4.0.0.

Fedora 35 will apparently not ship with podman 4, so I would like to install a version of this tool that is compatible with podman 3.4.4

**Comment by peacememories** [comment]
Confirmed that cloning the repo and going back to version 3.4.4 works perfectly fine. So I would love to have this version available on flathub, since that seems to be the latest stable version of podman on Fedora

**Comment by wcasanova** [comment]
can't they both be version 3 and 4 ?
currently there are 2 but they are version 3
`Podman (remote client)   A tool for VS Code for managing OCI containers and pods   com.visualstudio.code.tool.podman  3.4.7   21.08`
`Podman (remote client)   A tool for VS Code for managing OCI containers and pods   com.visualstudio.code.tool.podman  3.4.0   20.08`

**Comment by gasinvein** [comment]
Branch `20.08` is obsolete and unmaintained; it was there for the previous freedesktop sdk.
