### ISSUE TITLE
Podman 4 support?

### ISSUE THREAD

**Issue by CheariX** [flathub/com.visualstudio.code.tool.podman#21]
Fedora 36 ships with Podman 4 (currently: 4.1.1).
Are there any plans to update to this version?

```sh
> podman-remote version
Client:
Version:      3.4.7
API Version:  3.4.7
Go Version:   go1.18.1
Git Commit:   74d67f5d43bcd322a4fb11a7b58eced866f9d0b9
Built:        Fri Apr 22 20:55:41 2022
OS/Arch:      linux/amd64

Server:
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 15 16:31:58 2022
OS/Arch:      linux/amd64
```

**Comment by gasinvein** [comment]
It was once updated to v4, but then downgraded back to v3 due to #13 (v3 client is compatible with v3 server, but not vice versa).

**Comment by CheariX** [comment]
Any ETA for Podman 4 support?
Although i can connect to a podman-remote 4.x instance, building remote containers is not possible due to https://github.com/containers/podman/issues/13025

**Comment by CheariX** [comment]
Yes. I'm fine with having two different packages.

**Comment by gasinvein** [comment]
> it could also be helpful to put podman4 on flathub beta only?

You mean podman4 as additional binary, or in place of podman3?

> Btw. Fedora 37 ships podman 4.2.

Yeah, but current Ubuntu LTS and Debian stable still have 3.x (and most likely won't update until next release).

**Comment by CheariX** [comment]
OK. An additional binary is also a good solution. In summary, I see three possibilities:

1) Create a new  package `com.visualstudio.code.tool.podman4` in parallel to this package
2) Update this package to podman 4 but only publish it on Flathub beta
3) Add a second binary `podman4-remote` to this package.

For me, any of them works.

**Comment by CheariX** [comment]
Thank you.

```sh
flatpak uninstall com.visualstudio.code.tool.podman
flatpak install flathub-beta com.visualstudio.code.tool.podman
```

works like charm. Tested on Fedora 37.
