### ISSUE TITLE
Support for Visual Studio Code Insiders

### ISSUE THREAD

**Issue by rtmor** [flathub/com.visualstudio.code.tool.podman#33]
Hi @gasinvein!

I was wondering if you had any interest in maintaining an insiders version of this tool?

I went ahead and made the necessary modifications to support `com.visualstudio.code.insiders` and submitted an initial PR draft to Flathub when it occurred to me to reach out to you first.

If you have any issues or prefer to maintain the version yourself, let me know

Thanks,
Ryan

**Comment by gasinvein** [comment]
As pointed out in flathub/flathub#4125, instead of creating a duplicate extension, the app should be fixed to be compatible with the existing one.
