### ISSUE TITLE
How does this actually work?

### ISSUE THREAD

**Issue by FilBot3** [flathub/com.visualstudio.code.tool.podman#4]
I installed this, attempted to load the extension, and it didn't work. I see that it's not labeled as an extension and I don't know how the Code flatpak does that.

**Comment by gasinvein** [comment]
How it's labelled in metainfo doesn't really matter for flatpak. If the flatpak has `com.visualstudio.code.tool`, this tool, once installed, will appear under `/app/tools/podman` directory. If the flatpak sandbox environment is properly set up (e.g. by some wrapper), you'll have `podman-remote` command available in the sandbox.

To control local Podman instance on host with `podman-remote` in the sandbox, it needs access to Podman sockets in `$XDG_RUNTIME_DIR/podman`. E.g. running `flatpak override --user --filesystem=xdg-run/podman:ro com.visualstudio.code` will grant this permission to VSCode flatpak. Then you can use `podman-remote` in the built-in terminal.

**Comment by FilBot3** [comment]
Thank you very much! I was able to get something going. I may be missing other parts though.

* https://github.com/flathub/com.visualstudio.code/issues/55#issuecomment-913864265

**Comment by peacememories** [comment]
I installed `com.visualstudio.code.tool.podman` but it does not seem to get added to the path of my vscode flatpak. Am I missing something I need to activate here?
The override seems to have worked in the sense that the `podman.sock` is visible within the flatpak, but I do not get the executable
