### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by francoism90** [flathub/com.visualstudio.code.tool.podman#68]
```
$ FLATPAK_ENABLE_SDK_EXT=podman flatpak run --command=sh com.visualstudio.code
```
The `app/tools/podman` directory doesn't exists.

Anyone having the same problem?

**Comment by 0pendev** [comment]
Same issue on my end with latest version :cry:

**Comment by francoism90** [comment]
@0pendev Could you try: https://github.com/flathub/com.visualstudio.code.tool.podman/pull/67#issuecomment-2378360643

This seems to fix my issue.

**Comment by francoism90** [comment]
@0pendev You could try to build it yourself, but I also believe the maintainer can retrigger the build with a comment.

Let's hope it get's merged soon. :)

**Comment by 0pendev** [comment]
@francoism90 triggered the build on the merged and tested it. It works like a charm. Hope to see it merged soon :100:
